### ISSUE TITLE
What useful cluster/node/pinset metrics can we show using the GUI?

### ISSUE THREAD

**Issue by vasa-develop** [cluster-labs/horizon#7]
There are a few metrics that can be useful. Some of these are:
- `/health/graph` & `/health/metrics` endpoints for peerset metrics
- `/status` for pinset

What are the other metrics that we can show in a UI? 

@hsanjuan @lanzafame @kishansagathiya

**Comment by kishansagathiya** [comment]
I think these three things should be enough

**Comment by hsanjuan** [comment]
Use `/allocations` for pinset metrics (like the number of pins). `/status` (actually it's `/pins`) is a broadcast call that needs to contact every peer to report the status.

`/id` should give you a list of cluster peers (similar to peers shown by `/monitor/metrics`).

Other than that, the API doesn't expose much more.

**Comment by vasa-develop** [comment]
Closing this for now, as it seems to be resolved :)
